const MOCK_GROUPS = [
        {
            name: "Első",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Második",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Harmadik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Negyedik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Ötödik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Hatodik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Hetedik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Nyolcadik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Kilencedik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizedik",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenegy",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenkettő",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenhárom",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizennégy",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenöt",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenhat",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenhét",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizonnyolc",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Tizenkilenc",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Húsz",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonegy",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonkettő",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonhárom",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonnégy",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonöt",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonhat",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonhét",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonnyolc",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
        {
            name: "Huszonkilencs",
            wins: 0,
            losses: 0,
            draws: 0,
            thrown: 0,
            received: 0,
            points: 0,
        },
  ]

  export default MOCK_GROUPS
